/**
 * Offline support (app-shell service worker).
 *
 * The worker is generated by vite-plugin-pwa (generateSW) and served at /sw.js.
 * Registration is refused in dev, inside iframes, in Lovable preview hosts and
 * whenever ?sw=off is present — in those cases any stale registration for
 * /sw.js is removed instead.
 */

function isRefusedContext(): boolean {
  if (!import.meta.env.PROD) return true;
  try {
    if (window.self !== window.top) return true;
  } catch {
    return true;
  }
  const host = window.location.hostname;
  if (host.startsWith("id-preview--") || host.startsWith("preview--")) return true;
  if (host === "lovableproject.com" || host.endsWith(".lovableproject.com")) return true;
  if (host === "lovableproject-dev.com" || host.endsWith(".lovableproject-dev.com")) return true;
  if (host === "beta.lovable.dev" || host.endsWith(".beta.lovable.dev")) return true;
  if (new URLSearchParams(window.location.search).has("sw")) {
    if (new URLSearchParams(window.location.search).get("sw") === "off") return true;
  }
  return false;
}

async function unregisterAppWorkers() {
  if (!("serviceWorker" in navigator)) return;
  const registrations = await navigator.serviceWorker.getRegistrations();
  await Promise.allSettled(
    registrations
      .filter((registration) => {
        const url = registration.active?.scriptURL ?? registration.installing?.scriptURL ?? "";
        return url.endsWith("/sw.js");
      })
      .map((registration) => registration.unregister()),
  );
}

let waitingRegistration: ServiceWorkerRegistration | null = null;
const waitingListeners = new Set<() => void>();

function announceWaiting(registration: ServiceWorkerRegistration) {
  waitingRegistration = registration;
  waitingListeners.forEach((fn) => fn());
}

/** Fires when a newer app version is installed and waiting to take over. */
export function onWaitingWorker(fn: () => void) {
  waitingListeners.add(fn);
  if (waitingRegistration) fn();
  return () => {
    waitingListeners.delete(fn);
  };
}

/** Applies the waiting version and reloads. */
export function activateWaitingWorker() {
  const waiting = waitingRegistration?.waiting;
  if (!waiting) {
    window.location.reload();
    return;
  }
  waiting.postMessage({ type: "SKIP_WAITING" });
  navigator.serviceWorker.addEventListener("controllerchange", () => window.location.reload(), { once: true });
}

export function registerOfflineSupport() {
  if (typeof window === "undefined" || !("serviceWorker" in navigator)) return;
  if (isRefusedContext()) {
    void unregisterAppWorkers();
    return;
  }
  window.addEventListener("load", () => {
    void navigator.serviceWorker
      .register("/sw.js", { scope: "/" })
      .then((registration) => {
        if (registration.waiting) announceWaiting(registration);
        registration.addEventListener("updatefound", () => {
          const installing = registration.installing;
          if (!installing) return;
          installing.addEventListener("statechange", () => {
            if (installing.state === "installed" && navigator.serviceWorker.controller) {
              announceWaiting(registration);
            }
          });
        });
        // Look for a newer build every 30 minutes while the app stays open.
        window.setInterval(() => void registration.update(), 30 * 60 * 1000);
      })
      .catch(() => {
        /* offline support is best-effort */
      });
  });
}

