/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GpsRouteImport } from './routes/gps'
import { Route as SquadRouteImport } from './routes/squad'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as PlayersIdRouteImport } from './routes/players.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GpsRoute = GpsRouteImport.update({
  id: '/gps',
  path: '/gps',
  getParentRoute: () => rootRouteImport,
} as any)
const SquadRoute = SquadRouteImport.update({
  id: '/squad',
  path: '/squad',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIdRoute = PlayersIdRouteImport.update({
  id: '/players/$id',
  path: '/players/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gps': typeof GpsRoute
  '/squad': typeof SquadRoute
  '/training': typeof TrainingRoute
  '/players/$id': typeof PlayersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gps': typeof GpsRoute
  '/squad': typeof SquadRoute
  '/training': typeof TrainingRoute
  '/players/$id': typeof PlayersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gps': typeof GpsRoute
  '/squad': typeof SquadRoute
  '/training': typeof TrainingRoute
  '/players/$id': typeof PlayersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/gps' | '/squad' | '/training' | '/players/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/gps' | '/squad' | '/training' | '/players/$id'
  id: '__root__' | '/' | '/gps' | '/squad' | '/training' | '/players/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GpsRoute: typeof GpsRoute
  SquadRoute: typeof SquadRoute
  TrainingRoute: typeof TrainingRoute
  PlayersIdRoute: typeof PlayersIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gps': {
      id: '/gps'
      path: '/gps'
      fullPath: '/gps'
      preLoaderRoute: typeof GpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/squad': {
      id: '/squad'
      path: '/squad'
      fullPath: '/squad'
      preLoaderRoute: typeof SquadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$id': {
      id: '/players/$id'
      path: '/players/$id'
      fullPath: '/players/$id'
      preLoaderRoute: typeof PlayersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GpsRoute: GpsRoute,
  SquadRoute: SquadRoute,
  TrainingRoute: TrainingRoute,
  PlayersIdRoute: PlayersIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
